version: 2
jobs:
  pr_check:
    docker:
      - image: node:8.17.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: |
            ls -al
            pwd
            npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: install pip
          command: |
            apt-get update || sudo apt-get update
            apt-get install python3 -y
            python3 --version
            apt install python3-pip -y
            pip3 --version
            apt update && apt install -y zip unzip
      - run: 
          name: "Zip Artifacts"
          command: |
           echo "Hello the current build number is ${CIRCLE_BUILD_NUM}"
            pwd
            zip csye6225-lambda-${CIRCLE_BUILD_NUM}.zip index.js
      - run:
          name: install aws cli
          command: |
            pip3 install awscli
            mkdir ~/.aws 
            cd ~/.aws
            echo -e "[default]\naws_access_key_id=$aws_access_key\naws_secret_access_key=$aws_secret_key\n" > ~/.aws/credentials
      - run:
          name: Upload Artifact to S3
          command: |
            aws s3 cp csye6225-lambda-${CIRCLE_BUILD_NUM}.zip s3://${bucketName}
      - run:
          name: Update lambdaFunction code
          command: |
            aws lambda update-function-code --function-name MyLambdaFunction --region us-east-1 --zip-file fileb://csye6225-lambda-${CIRCLE_BUILD_NUM}.zip
      
  build:
    docker:
      - image: node:8.17.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "webapp/package.json" }}
            - v1-dependencies-
      - run: |
            cd webapp
            ls -al
            pwd
            npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "webapp/package.json" }}
      - run: 
          name: "Test"
          command: |
            pwd
            cd webapp
            ls -al
            pwd
            npx jest
            echo 'Done'
      - run:
          name: install pip
          command: |
            apt-get update || sudo apt-get update
            apt-get install python3 -y
            python3 --version
            apt install python3-pip -y
            pip3 --version
            apt update && apt install -y zip unzip
      - run: 
          name: "Zip Artifacts"
          command: |
           echo "Hello the current build number is ${CIRCLE_BUILD_NUM}"
            pwd
            zip csye6225-lambda-${CIRCLE_BUILD_NUM}.zip index.js
      - run:
          name: install aws cli
          command: |
            pip3 install awscli
            mkdir ~/.aws 
            cd ~/.aws
            echo -e "[default]\naws_access_key_id=$aws_access_key\naws_secret_access_key=$aws_secret_key\n" > ~/.aws/credentials
      - run:
          name: Upload Artifact to S3
          command: |
            cd codedeploy_artifact
            aws s3 cp csye6225-lambda-${CIRCLE_BUILD_NUM}.zip s3://${bucketName}
      - run:
          name: Update lambdaFunction code
          command: |
            echo Updating 
            aws lambda update-function-code --function-name MyLambdaFunction --region us-east-1 --zip-file fileb://csye6225-lambda-${CIRCLE_BUILD_NUM}.zip
      
workflows:
  version: 2
  pr_check_workflow:
    jobs:
      - pr_check
  build_deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master
          

      
      
  
    
      